# Generated by Django 4.1.7 on 2023-03-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hender',
            field=models.CharField(choices=[('K', 'Детский'), ('W', 'Женский'), ('ALL', 'Все'), ('M', 'Мужской')], default='ALL', max_length=3),
        ),
    ]
